apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: sentinelops-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
      annotations:
        sentinelops.io/change-cause: healthy-baseline
        sentinelops.io/health-status: healthy
    spec:
      containers:
        - name: inventory-service
          image: sentinelops-demo-services:local
          imagePullPolicy: Never
          env:
            - name: SERVICE_NAME
              value: inventory-service
            - name: SERVICE_ROLE
              value: inventory
            - name: FAIL_EVERY
              value: "0"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector:4318
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 2
            periodSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: sentinelops-demo
spec:
  selector:
    app: inventory-service
  ports:
    - port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: sentinelops-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: sentinelops-demo-services:local
          imagePullPolicy: Never
          env:
            - name: SERVICE_NAME
              value: order-service
            - name: SERVICE_ROLE
              value: order
            - name: INVENTORY_URL
              value: http://inventory-service:8000
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector:4318
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 2
            periodSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: sentinelops-demo
spec:
  selector:
    app: order-service
  ports:
    - port: 8000
      targetPort: 8000
